#!/usr/bin/env perl
# martin, 2018-12-05

use strict;
use warnings;
use utf8;
use v5.16.0;

my $usage = <<'EOF';
Prints multiple coherent lines of Sido's "Mein Block"
before passing its arguments to sudo.

  sido touch /root/foo

EOF

binmode(STDIN,  ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');

my @lyrics = (
  [
   "Du in deinem Einfamilienhaus lachst mich aus",
   "Weil du denkst du hast alles was du brauchst"
  ],
  [
   "Doch im MV scheint mir die Sonne ausm Arsch",
   "In meinem Block weiß jeder: Wir sind Stars"
  ],
  [
   "Hier kriege ich alles",
   "Ich muss hier nicht mal weg",
   "Hier hab ich Drogen, Freunde und Sex"
  ],
  [
   "Die Bullen können kommen, doch jeder weiß Bescheid",
   "Aber keiner hat was geseh'n also können sie wieder gehen"
  ],
  [
   "Ok, ich muss gesteh'n: hier ist es dreckich wie 'ne Nutte",
   "Doch, ich glaub das wird schon wieder mit 'n bisschen Spucke"
  ],
  [
   "Mein schöner weißer Plattenbau wird langsam grau",
   "Draufgeschissen! Ich werd auch alt und grau im MV"
  ],
  [
   "Meine Stadt, mein Bezirk, mein Viertel, meine Gegend",
   "Meine Straße, mein Zuhause, mein Block"
  ],
  [
   "Meine Gedanken, mein Herz, mein Leben",
   "Meine Welt reicht vom ersten bis zum 16. Stock"
  ],
  [
   "Der Kerl aus'm ersten war früher mal Rausschmeißer!",
   "Seit dem er aus dem Knast ist, ist er unser Hausmeister"
  ],
  [
   "Er ist oft bei der Nutte aus dem Zweiten",
   "Jetzt verkauft sie Fotos von ihm beim Arschausweiten"
  ],
  [
   "Der Fetischist aus dem 5. kauft sie gerne",
   "Er sagt, Rosetten sehen aus wie kleine Sterne!"
  ],
  [
   "Obwohl die von dem Schwulen aus dem 11. immer aussieht",
   "Als wenn man den Schwanz gerade frisch rauszieht!"
  ],
  [
   "Und davon sing ich dir ein Lied, du kannst es kaufen",
   "wie die Sekte Fans aus'm 9. die immer drauf sind"
  ],
  [
   "Genauso wie der Junkie aus'm 4.",
   "Der zum Frühstück erstmal 10 Bier trinkt",
  ],
  [
   "Dann geht er hoch in den 7. zum Ticker",
   "Er bezahlt für 10 Teile doch statt Gras kriegt er nen Ficker"
  ],
  [
   "Damals war der Drogenstock noch der 10.",
   "Der aus'm 7. ist der, der überlebte"
  ],
  [
   "Hier kriegst du alles",
   "Im 12. bei Manne kriegste du Falschgeld",
   "Und ein Bootleg von Eißfeldt"
  ],
  [
   "Ein Stock höher hat so 'n Kerl sein Studio",
   "Er rappt und macht Tracks auf die Beats von Coolio"
  ],
  [
   "Ganz zur Freude der Hausfrau darüber",
   "Die sagt: „Männer ficken auch nicht mehr wie früher“"
  ],
  [
   "Deshalb trifft man sie oft im 15. Stock bei der Hardcore-Lesbe",
   "Mit dem Kopf unter ihrem Rock"
  ],
  [
   "Wenn ich ficken will fahr ich runter in den 3.",
   "Aber die Braut fick ich nur zwischen die Titten"
  ],
  [
   "Denn der Pornostock befindet sich im 8.",
   "Hier könnt' ich jeden Tag woanders übernachten"
  ],
  [
   "Im 16. Stock riecht der Flur voll streng",
   "Aus der Wohnung wo so 'n Kerl schon seit drei Wochen hängt"
  ],
  [
   "Ich häng im 6. rum in meinem Stock",
   "Mit meinem übergeilen Nachbarn in meinem Block"
  ],
  [
   "Deine Villa, dein Boot, deine Frauen",
   "Deine Karriere, dein Geld, dein Leben"
  ],
  [
   "Kein Bock, kein Bock"
  ]
);

if (scalar @ARGV && $ARGV[0] =~ /-[hu]/) {
  print $usage;
  exit;
}

print join("\n", @{$lyrics[rand @lyrics]}), "\n\n";
unshift(@ARGV, 'sudo');
print qx/@ARGV/;
